### PR TITLE
update deprecated function nonce_user_logged_out

### PR DESCRIPTION
**Pull request by glagonikas**
Resolves https://github.com/skyverge/wc-plugin-framework/issues/541 and https://github.com/woocommerce/facebook-for-woocommerce/issues/1966 Other Skyverge plugins like Social Login and Address Validation use this code and should benefit from this change

### CODE REVIEW

**Comment by glagonikas** [comment]
@unfulvio @adrianostanley apologies for mentioning you directly. Any change you can review and merge this, so the change propagates to all other Skyverge plugins soon?

**Comment by unfulvio** [comment]
@glagonikas thanks for your PR and the heads up!
It looks like this is solvable with your proposed PR - we just need a backwards compatibility check for older WC versions so either callback can be supported.
We need to update all plugins that utilize this in order to get rid of the deprecated notice.

**Comment by glagonikas** [comment]
@unfulvio PR updated with backwards compatibility

**Comment by glagonikas** [comment]
Ah, I notice you've already made a PR for it. I'll close mine then

**Comment by unfulvio** [comment]
hey sorry about that, yeah I wanted to go with our internal processes, plus utilize some internal helpers - I also noticed that the number of arguments passed from action to callback changed so it needs to account for that

**Pull request closed without merging**
