### PR TITLE
4.3

### PR DESCRIPTION
**Pull request by ChaseWiseman**
# To Do

* [x] create compatibility methods for [`wc_site_is_https()`](https://github.com/woothemes/woocommerce/blob/ad11042afdec60a4571586e97386656504cd684f/includes/wc-conditional-functions.php#L366-L368) and  [`wc_checkout_is_https()`](https://github.com/woothemes/woocommerce/blob/ad11042afdec60a4571586e97386656504cd684f/includes/wc-conditional-functions.php#L376-L378) -- ceb03cf8f26baae99bce3baf80b3c284be2d0e53
   * [x] Update the admin notice [SSL check](https://github.com/skyverge/wc-plugin-framework/blob/328c2524f3c8f881d7dd7e8124176355dc784257/woocommerce/payment-gateway/class-sv-wc-payment-gateway-plugin.php#L385) to use the new `wc_checkout_is_https()` compatibility method

* [x] Remove the `SV_WC_API_REST_Request` class now that we have a base JSON request class. Check for usages, but I think the only one is in WC <> Jilt, which can be updated to work with this latest release. **Completed in** -- SHA 62caef152a5e9c60b6217fb7e47829d172be22b9
    * [ ] AvaTax

* [x] Edit the JSON request `to_string()` method to removed the `http_build_query()` as it's not appropriate for a JSON style request. It should be similar to the XML method in retrieving the request data and JSON-encoding it.
    * **Completed in** -- SHA b6b661fa6cee8bd1577480d7da1fc9f7ea4add6f

* [x] Rename .pot file to `woocommerce-plugin-framework.pot` to match the current text domain :innocent:

    * **Completed in** -- SHA 62caef152a5e9c60b6217fb7e47829d172be22b9

## Gateway changes required
* `iconv` is no longer a dependency
* hooks can be deprecated via the hook deprecator class
* `SV_WC_Payment_Gateway_API_Payment_Notification_Response::get_payment_type()` moved to `SV_WC_Payment_Gateway_API_Response::get_payment_type()`.
* Add `FEATURE_TOKEN_EDITOR` to gateways that support tokenization and confirm it works
* Tokenization methods are moved from the direct gateway class into their own class. Implementing gateways that override tokenization methods will need to adapt
* Hosted gateway class has been refactored a bit and implementing gateways may need adjustments.
* Test handling of saved payment methods that are used for active subscriptions. It should prevent you from deleting them.

### Associated release issues [here](https://github.com/skyverge/wc-plugins/issues?q=is%3Aopen+is%3Aissue+label%3Aframework-4.3.0)

### CODE REVIEW

**Comment by tamarazuk** [comment]
added todos:

> * [ ] create compatibility methods for [`wc_site_is_https()`](https://github.com/woothemes/woocommerce/blob/ad11042afdec60a4571586e97386656504cd684f/includes/wc-conditional-functions.php#L366-L368) and  [`wc_checkout_is_https()`](https://github.com/woothemes/woocommerce/blob/ad11042afdec60a4571586e97386656504cd684f/includes/wc-conditional-functions.php#L376-L378) 
   * [ ] Update the admin notice [SSL check](https://github.com/skyverge/wc-plugin-framework/blob/328c2524f3c8f881d7dd7e8124176355dc784257/woocommerce/payment-gateway/class-sv-wc-payment-gateway-plugin.php#L385) to use the new `wc_checkout_is_https()` compatibility method

**Comment by tamarazuk** [comment]
added:

> * [ ] Rename .pot file to `woocommerce-plugin-framework.pot` to match the current text domain :innocent:

**Comment by ChaseWiseman** [comment]
@maxrice whenever you're able this is ready for review before we merge and start on the gateways :smile:

**Comment by maxrice** [comment]
@ChaseWiseman really outstanding work on the token editor, tested it with First Data and it worked well. I made a few tweaks for you to review. Otherwise, our next steps are:

* add JS validation to the last four/expiry fields
* add a "make default" action button so the admin editor mirrors what a customer can do
* add a save button to the lower left of the table so admins don't have to scroll all the way down to save the form

After that, I think we're ready to version this `4.3.0-beta` and start the process of testing/integrating with the frameworked gateways (and AvaTax).

**Comment by tamarazuk** [comment]
🎊

**Pull request merged**
