### PR TITLE
validate_fields return consistency

### PR DESCRIPTION
**Pull request by tivnet**
- `$this->$method_name( $is_valid );` looks like missing return?
- default return is missing, too. I guess, it's `true`?

### CODE REVIEW

**Comment by justinstern** [comment]
@tivnet good catch here. Just change that final `return true;` to `return $is_valid;` so that we're returning whatever the parent method returned, by default

**Comment by tivnet** [comment]
@justinstern ops. Of course, `return $is_valid;`. Thank you!

**Comment by justinstern** [comment]
:+1:

**Comment by maxrice** [comment]
merged into 4.1 with SHA 0c1db330f3b767aedb6632e333676e9325d2b0da

**Pull request closed without merging**
